import { Need, NeedStatus, District, Person, Event, Volunteer } from '../types';

export const INITIAL_NEEDS: Need[] = [
  {
    id: '1',
    item: 'Drinking Water',
    category: 'WATER',
    urgency: 'HIGH',
    affectedCount: 150,
    demographics: { men: 40, women: 60, children: 50 },
    quantity: 50,
    pledgedAmount: 20,
    receivedAmount: 10,
    unit: 'Bottles (5L)',
    district: District.RATNAPURA,
    location: 'Flood Relief Camp, Ratnapura Town Hall',
    coordinates: { lat: 6.6797, lng: 80.3992 },
    contactName: 'Saman Perera',
    contactNumber: '0771234567',
    status: NeedStatus.REQUESTED,
    createdAt: Date.now() - 100000,
    type: 'GOODS',
  },
  {
    id: '2',
    item: 'Dry Rations Packs',
    category: 'FOOD',
    urgency: 'MEDIUM',
    affectedCount: 50,
    demographics: { men: 15, women: 20, children: 15 },
    quantity: 100,
    pledgedAmount: 100,
    unit: 'Packs',
    district: District.GALLE,
    location: 'Neluwa Community Center',
    coordinates: { lat: 6.2056, lng: 80.3642 },
    contactName: 'Galle DRO',
    contactNumber: '0912223333',
    status: NeedStatus.PLEDGED,
    createdAt: Date.now() - 200000,
    type: 'GOODS',
  },
  {
    id: '3',
    item: 'Baby Milk Powder',
    category: 'BABY_ITEMS',
    urgency: 'HIGH',
    affectedCount: 20,
    demographics: { men: 0, women: 0, children: 20 },
    quantity: 20,
    pledgedAmount: 5,
    unit: 'Tins (400g)',
    district: District.KALUTARA,
    location: 'Bulathsinhala Temple',
    coordinates: { lat: 6.6472, lng: 80.1772 },
    contactName: 'Rev. Sobitha',
    contactNumber: '0342224444',
    status: NeedStatus.REQUESTED,
    createdAt: Date.now() - 50000,
    type: 'GOODS',
  },
  {
    id: '4',
    item: 'Well Cleaning',
    category: 'CLEANUP',
    urgency: 'MEDIUM',
    affectedCount: 10,
    district: District.GAMPAHA,
    location: 'Ja-Ela Main Road',
    coordinates: { lat: 7.0780, lng: 79.8900 },
    contactName: 'Community Leader',
    contactNumber: '0775556666',
    status: NeedStatus.REQUESTED,
    createdAt: Date.now() - 10000,
    type: 'SERVICE',
    description: 'Need help cleaning 5 wells contaminated by flood water.',
  },
  {
    id: '5',
    item: 'Road Clearing',
    category: 'LOGISTICS',
    urgency: 'HIGH',
    affectedCount: 500,
    district: District.MATARA,
    location: 'Akuressa - Deniyaya Road',
    coordinates: { lat: 6.1500, lng: 80.5000 },
    contactName: 'Pradeshiya Sabha',
    contactNumber: '0412223333',
    status: NeedStatus.REQUESTED,
    createdAt: Date.now() - 5000,
    type: 'SERVICE',
    description: 'Fallen trees blocking the main road. Need chainsaw operators.',
  }
];

export const INITIAL_PEOPLE: Person[] = [
  {
    id: '1',
    name: 'Kamal Gunaratne',
    district: District.RATNAPURA,
    status: 'SAFE',
    lastSeenLocation: 'Ratnapura Hospital',
    coordinates: { lat: 6.6820, lng: 80.4000 },
    reportedBy: 'Self',
    updatedAt: Date.now(),
    message: 'I am safe with my family at the hospital camp.',
  },
  {
    id: '2',
    name: 'Nimali Silva',
    district: District.MATARA,
    status: 'MISSING',
    lastSeenLocation: 'Akuressa Main Road',
    coordinates: { lat: 6.0983, lng: 80.4633 },
    reportedBy: 'Husband',
    updatedAt: Date.now() - 3600000,
    contactNumber: '0718889999',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Post-Flood Cleanup: Ratnapura City',
    description: 'Cleaning mud and debris from the main bus stand area.',
    district: District.RATNAPURA,
    location: 'Ratnapura Bus Stand',
    coordinates: { lat: 6.6780, lng: 80.3980 },
    date: '2023-11-15',
    time: '08:00 AM',
    requiredVolunteers: 50,
    registeredVolunteers: 12,
    type: 'CLEANUP',
  },
  {
    id: '2',
    title: 'Dry Ration Distribution: Kalutara',
    description: 'Packing and distributing dry rations to affected families.',
    district: District.KALUTARA,
    location: 'Kalutara Bodhiya Premises',
    coordinates: { lat: 6.5854, lng: 79.9607 },
    date: '2023-11-16',
    time: '09:00 AM',
    requiredVolunteers: 20,
    registeredVolunteers: 20,
    type: 'DISTRIBUTION',
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: '1',
    name: 'Kasun Perera',
    contactNumber: '0771112222',
    district: District.COLOMBO,
    location: 'Colombo 03',
    coordinates: { lat: 6.9061, lng: 79.8640 },
    skills: ['GOODS', 'SERVICES'],
    coverageArea: 'Colombo District',
    status: 'AVAILABLE',
    joinedAt: Date.now() - 1000000,
  },
  {
    id: '2',
    name: 'Dr. Ruwan',
    contactNumber: '0714445555',
    district: District.GALLE,
    location: 'Karapitiya',
    coordinates: { lat: 6.0635, lng: 80.2354 },
    skills: ['SERVICES', 'LABOR'],
    coverageArea: '10km Radius',
    status: 'BUSY',
    joinedAt: Date.now() - 500000,
  },
];